name: "ClapTrap-CUSTOM"
version: "2.2.3"
slug: "claptrap"
description: "Application de détection d'applaudissements en temps réel utilisant YAMNet, compatible avec les flux audio locaux et RTSP"
url: "https://github.com/JulienDeveaux/ClapTrap-HA-Addon"
init: false
maintainer: "JulienDeveaux"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addon_config:rw
options:
  global:
    threshold: 0.5
    delay: 1.0
    chunk_duration: 0.5
    buffer_duration: 1.0
  mqtt_client_id: claptrap_mqtt_client
  mqtt_host: 192.168.1.x
  mqtt_username: user
  mqtt_password: xxxx
  mqtt_port: 1883
  mqtt_topic: claptrap
  microphone:
    device_index: 0
    audio_source: default
    enabled: False
  rtsp:
    - id: 1
      url: rtsp://username:password@ip_address:port/stream
      name: Camera 1
      enabled: False
  vban:
    - ip: 0.0.0.0
      steam_name: vban_stream
      port: 6980
      enabled: False

schema:
  log_level: list(debug|info|warning|error)?
  global:
    threshold: float?
    delay: float?
    chunk_duration: float?
    buffer_duration: float?
  mqtt_client_id: str?
  mqtt_host: str?
  mqtt_username: str?
  mqtt_password: password?
  mqtt_port: int?
  mqtt_topic: str?
  microphone:
    device_index: int?
    audio_source: str?
    enabled: bool?
  rtsp:
    - id: int?
      url: str?
      name: str?
      enabled: bool?
  vban:
    - ip: str?
      steam_name: str?
      port: int?
      enabled: bool?
